blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include
from django.contrib import admin
from accounts.views import (login_view, register_view, logout_view)
from rest_framework_jwt.views import obtain_jwt_token
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^comments/', include("comments.urls" , namespace='comments')),
    url(r'^login/', login_view, name="login"),
    url(r'^logout/', logout_view, name="logout"),
    url(r'^register/', register_view, name="register"),
    url(r'^', include("posts.urls" , namespace='posts')),
     url(r'^api/auth/token/', obtain_jwt_token),
    url(r'^api/comments/', include("comments.api.urls" , namespace='comments-api')),
    url(r'^api/posts/', include("posts.api.urls" , namespace='posts-api')),
    url(r'^api/users/', include("accounts.api.urls" , namespace='users-api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/api/urls.py
from django.conf.urls import url,include
from .views import (
    PostDetailAPIView,
    PostUpdateAPIView,
    PostDeleteAPIView,
    PostCreateAPIView,
    PostListAPIView
)
urlpatterns = [
    url(r'^$', PostListAPIView.as_view(), name="list"),
    url(r'^create$', PostCreateAPIView.as_view(), name="create"),
    url(r'^(?P<slug>[\w-]+)/$', PostDetailAPIView.as_view(), name="detail"),
    url(r'^(?P<slug>[\w-]+)/edit/$', PostUpdateAPIView.as_view(), name="update"),
    url(r'^(?P<slug>[\w-]+)/delete/$', PostDeleteAPIView.as_view(), name="delete"),
]

posts/urls.py
from django.conf.urls import url,include
from . import views
urlpatterns = [
    url(r'^$', views.post_list, name="list"),
    url(r'^create$', views.post_create),
    url(r'^(?P<slug>[\w-]+)/$', views.post_detail, name="detail"),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.post_update, name="update"),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.post_delete),
]

posts/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.contrib.contenttypes.models import ContentType
from markdown_deux import markdown
from django.utils.safestring import mark_safe
from comments.models import Comment
from .utils import get_read_time
# Create your models here.

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    return '%s/%s' %(instance.id, filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    draft = models.BooleanField(default = False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    read_time = models.TimeField(null=True,blank=True)
    image = models.ImageField(upload_to= upload_location
    , null = True, blank = True, height_field="height_field", width_field="width_field")
    height_field = models.IntegerField(default = 0)
    width_field = models.IntegerField(default = 0)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    objects = PostManager()
    def __str__(self):
        return self.title

    def get_markdown(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type

    def get_api_url(self):
        return reverse("posts-api:detail", kwargs= {"slug" : self.slug})

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs= {"slug" : self.slug})

    def get_delete_url(self):
        return reverse("posts:delete", kwargs= {"slug" : self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.get_markdown()
        read_time_var = get_read_time(html_string)
        instance.read_time = read_time_var


pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms
from pagedown.widgets import PagedownWidget
from .models import Post

class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
            "draft",
            "publish",
        ]

posts/api/views.py
from django.db.models import Q

from rest_framework.filters import (
    SearchFilter,
    OrderingFilter,
)


from rest_framework.generics import(
    ListAPIView,
    RetrieveAPIView,
    UpdateAPIView,
    DestroyAPIView,
    RetrieveUpdateAPIView,
    CreateAPIView
    )

from posts.models import Post
from .serializers import (
    PostListSerializer,
    PostDetailSerializer,
    PostCreateUpdateSerializer
     )

from .permissions import IsOwnerOrReadOnly
from .pagination import PostLimitOffsetPagination, PostPageNumberPagination

from rest_framework.permissions import(
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly,
)

class PostCreateAPIView(CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer
    # permission_classes = [IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

class PostListAPIView(ListAPIView):
    serializer_class = PostListSerializer
    filter_backends = [SearchFilter, OrderingFilter]
    permission_classes = [AllowAny]
    search_fields = ['title', 'content', 'user__first_name']
    pagination_class = PostPageNumberPagination   #[PostLimitOffsetPagination, PostPageNumberPagination]

    def get_queryset(self, *args, **kwargs):
        queryset_list = Post.objects.all()
        query = self.request.GET.get("q")
        if query:
            queryset_list = queryset_list.filter(Q(title__icontains=query) | Q(content__icontains=query) | Q(user__first_name__icontains=query) | Q(user__last_name__icontains=query)).distinct()
        return queryset_list

class PostUpdateAPIView(RetrieveUpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer
    lookup_field = 'slug'
    permission_classes = [IsOwnerOrReadOnly]
    def perform_update(self, serializer):
        serializer.save(user=self.request.user)

class PostDeleteAPIView(DestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    lookup_field = 'slug'
    permission_classes = [IsOwnerOrReadOnly]


class PostDetailAPIView(RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    permission_classes = [AllowAny]
    lookup_field = 'slug'

posts/views.py
from urllib.parse import quote_plus
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from .forms import PostForm
from .models import Post
from comments.models import Comment
from comments.forms import CommentForm
def post_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Successfully created ")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "form" : form,
    }
    return render(request, "posts/form.html", context)

def post_detail(request, slug=None):
    today = timezone.now().date()
    instance = get_object_or_404(Post, slug=slug)
    if instance.draft or instance.publish > timezone.now().date():
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404


    share_string = quote_plus(instance.content)
    initial_data = {
        "content_type" : instance.get_content_type,
        "object_id" : instance.id
    }
    form = CommentForm(request.POST or None, initial=initial_data)
    if form.is_valid() and request.user.is_authenticated():
        c_type = form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model=c_type)
        obj_id = form.cleaned_data.get("object_id")
        content_data = form.cleaned_data.get("content")
        parent_obj = None
        try:
            parent_id = int(request.POST.get("parent_id"))
        except:
            parent_id = None

        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()


        new_comment, created = Comment.objects.get_or_create(user=request.user, content_type=content_type, object_id=obj_id, content=content_data, parent = parent_obj,)
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())
    comments = instance.comments
    context = {
        "instance" : instance,
        "title" : instance.title,
        "share_string" : share_string,
        "today":today,
        "comments":comments,
        "comment_form" : form,
    }
    return render(request, "posts/detail.html", context)

def post_list(request):
    queryset_list = Post.objects.active()#.order_by("-timestamp")
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Post.objects.all()

    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(Q(title__icontains=query) | Q(content__icontains=query) | Q(user__first_name__icontains=query) | Q(user__last_name__icontains=query)).distinct()
    paginator = Paginator(queryset_list, 5)

    page = request.GET.get('page')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)
    context = {
        "obj_list" : queryset
    }
    return render(request, "posts/postlist.html", context)
    #return HttpResponse("list")





def post_update(request ,slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Successfully created ")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "instance" : instance,
        "title" : instance.title,
        "form" : form,
    }
    return render(request, "posts/form.html", context)

def post_delete(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    instance.delete()
    messages.success(request, "Successfully deleted ")
    return redirect("posts:list")

posts/templates/posts/base.html
<html>
  <head>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
      {% load staticfiles %}
    <link rel="stylesheet" href = "{% static 'posts/css/base.css' %}"/>
    <title>{% block head %} Blog {% endblock head %}</title>
    {% block head_extra %}{{form.media}}{% endblock %}
  </head>
  <body>
    <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.10";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

    {% include "posts/messages.html" %}
    <div class = "container">
      <ol class="breadcrumb">
        <li><a href = '{% url "posts:list" %}'>Home</li>
          {% block post_detail_link %}
          {% endblock %}

          {% if not request.user.is_authenticated %}
        <li class="pull-right"><a href = '{% url "register" %}'>Register</a></li>
        <li class="pull-right"><a href = '{% url "login" %}'>Login</a></li>
          {% else %}
        <li class="pull-right"><a href = '{% url "logout" %}'>Logout</a></li>
          {% endif %}
      </ol>
      {% block content %}

      {% endblock content %}
    </div>
  </body>
</html>

<!-- Latest compiled and minified JavaScript -->
<script
  src="http://code.jquery.com/jquery-1.12.4.min.js"
  integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
  crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"
></script>
<script type="text/javascript">
$(document).ready(function(){
  $(".content-markdown").each(function(){
    var content = $(this).text()
    var markedcontent = marked(content)
    $(this).html(markedcontent)
  })
  $(".content-markdown img").each(function(){
    $(this).addClass("img-responsive")
  })

  var contentInput = $("#id_content");

  function setContent(value){
    var markedContent = marked(value)
    $("#preview-content").html(markedContent)
    $("#preview-content img").each(function(){
      $(this).addClass("img-responsive")
    })
  }
  setContent(contentInput.val())

  contentInput.keyup(function(){
    var newContent = $(this).val()
    setContent(newContent)
  })

  var titleInput = $("#id_title");

  function setTitle(value){
    $("#preview-title").text(value)
  }

  setTitle(titleInput.val())

  titleInput.keyup(function(){
    var newContent = $(this).val()
    setTitle(newContent)
  })

  $(".comment-reply-btn").click(function(event){
    event.preventDefault();
    $(this).parent().next(".comment-reply").fadeToggle();

  })

})
</script>

posts/templates/posts/detail.html
{% extends "posts/base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}
{% block head %} {{instance.title}}| {{block.super}} {% endblock head %}

{% block post_detail_link %}
<li><a href="{{instance.get_absolute_url}}">{{instance.title}}</a></li>
{% endblock %}

{% block content %}
    <h1>{{title}}</h1><br>
    <p>Read Time: {{instance.read_time|time:"i"}} minutes</p>
    {% if instance.user.get_full_name %}
    <p>Author: {{ instance.user.get_full_name }}</p>
    {% endif %}
    <br>
    {% if instance.draft %}
      <span style='color:red;'>Draft</span>
    {% endif %}
    <div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="standard" data-action="like" data-size="small" data-show-faces="false" data-share="true"></div>
    <hr>
      {% if instance.image %}
      <img src="{{ instance.image.url }}" class= "img-responsive" >
      {% endif %}
      <br>
      {{instance.publish}}
      <br>
      <br>
      <div class="content-markdown">{{ instance.content }}</div>
      <hr>
      <div>
      <p class="lead">Comments<p>
        {% if request.user.is_authenticated %}
        <form method="POST" action="."> {% csrf_token %}
        {{ comment_form|crispy }}
        <br>
        <input type = "submit" value="Post comment" class="btn btn-default">
      </form>
      {% else %}
      <p>you must login to comment</p>
      {% endif %}
        {% for comment in comments %}
          <blockquote class="blockquote">
              <p>{{comment.content}}</p>
              <footer class="blockquote-footer">by {{comment.user}} | {{comment.timestamp|timesince}} ago | {% if comment.children.count > 0  %} {{comment.children.count}} Comment{% if comment.children.count > 1  %}s{% endif %} | {% endif %}<a class="comment-reply-btn" href="#">Reply</a> | <a class="" href="{{ comment.get_absolute_url }}">Thread</a></footer>
            <div class="comment-reply">
              {% for child_comment in comment.children %}
              <blockquote class="blockquote">
                  <p>{{child_comment.content}}</p>
                  <footer class="blockquote-footer">by {{child_comment.user}} {{child_comment.timestamp|timesince}}</footer>
              </blockquote>
              {% endfor %}
              {% if request.user.is_authenticated %}
            <form method="POST" action="."> {% csrf_token %}
            {{ comment_form|crispy }}
            <br>
            <input type= "hidden" name="parent_id" value="{{ comment.id }}">
            <input type = "submit" value="Reply" class="btn btn-default">
          </form>
          {% else %}
          <p>you must login to comment</p>
          {% endif %}
        </div>
        </blockquote>
            <hr>
        {% endfor %}
      </div>
      <!-- <div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5"></div> -->
      <!-- {{ instance.content|urlify }} -->
      <!-- <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">Facebook
      </a>
    <a href="https://twitter.com/home?status={{ instance.content|urlify }}%20{{ request.build_absolute_uri }}">Twitter
    </a> -->
  {% endblock content%}

posts/templates/posts/form.html
{% extends "posts/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class = "col-sm-6">
  <h1 class="text-center">Preview</h1>
  <hr>
  <div class="content-preview">
    <h3 id="preview-title"></h3>
    <p id="preview-content"></p>
  </div>
</div>
  <div class="col-sm-6">
    <form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
    <h1>Form</h1>
    <hr>
    {{ form|crispy }}
    <input type="submit" class="btn btn-default" value="create post">
  </form>
</div>
{% endblock content %}

posts/templates/posts/messages.html
{% if messages %}
<div class="messages">
  <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
</div>
{% endif %}

posts/templates/posts/postlist.html
{% extends "posts/base.html" %}
{% block content %}
<h1>List</h1>
<div class="row">
  <form method="GET" action="">
      <div class="col-sm-8">
          <div class="input-group">
            <input class="form-control" type="text" name="q" placeholder="search posts" value= {{ request.GET.q }} >
            <span class="input-group-btn">
              <!-- <input class="btn btn-default" type="submit" value="submit"/> -->
              <button class="btn btn-default" type="submit"><i class="fa fa-search"></i>n</button>
            </span>
          </div>
        </div>
  </form>

{% for obj in obj_list %}
  <div class="col-sm-12">
    <div class="thumbnail">
      {% if obj.image %}
      <img src="{{ obj.image.url }}" class= "img-responsive" >
      {% endif %}
      <div class="caption">
        {% if obj.draft %}<h3>Draft{% if obj.publish > today %}<h3>Future Post</h3>{% endif %}</h3>{% endif %}
        <h3><a href = "{{ obj.get_absolute_url }}">{{obj.title}}</a> <small>{{obj.publish}}</small></h3>
        {% if instance.user.get_full_name %}
        <p>Author: {{ obj.user.get_full_name }}</p>
        {% endif %}
        <div class="content-markdown">{{obj.content}}</div>
        <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">view</a> </p>
      </div>
    </div>
  </div>
{% endfor %}
<div class="pagination">
    <span class="step-links">
        {% if obj_list.has_previous %}
            <a href="?page={{ obj_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ obj_list.number }} of {{ obj_list.paginator.num_pages }}.
        </span>

        {% if obj_list.has_next %}
            <a href="?page={{ obj_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>

</div>
{% endblock content %}